#!/bin/bash

# Version Kontrolle LG

# Eine Funktion um ein neues Projekt zu initialisieren
function init() {
    PROJECT_NAME=$1
    mkdir "$PROJECT_NAME"
    echo "Neues Projekt '$PROJECT_NAME' erstellt!"
}

# Die Hauptbedienfunktion, die die Befehle verarbeitet
if [[ $1 == "init" ]]; then
    init "$2"
else
    echo "Verwendung: ./version-kontrolle init <Projektname>"
fi
